import { RulesRecord } from './types';

export const rules: RulesRecord = {
  startProgram: /\bbem amigos da rede globo/,
  consoleLog: /\bolha o que ele fez/,
  keywordWhile: /\bla vem eles de novo/,
  keywordBreak: /\bcala boca galvao/,
  keywordFor: /\bvirou passeio/,
  keywordIf: /\bpode isso Arnaldo/,
  keywordElseIf: /\bvai ganhar ou vai perder/,
  keywordElse: /\bperdeu/,
  keywordFunction: /\bfez ali uma graça/,
  keywordReturn: /\be tetraaaaaa/,
  keywordTry: /\bsai que e sua tafarel/,
  keywordCatch: /\bhaaaaaja coraçao/,
  keywordFinally: /\bfim de papo/,
  keywordVar: /\be o nome dele/,
  keywordConst: /\be pentaaa/,
  keywordThrow: /\bolha o lançamentooo/,
  number: /[0-9]+/,
  // number: { match: /[0-9]+/, value: (state) => Number(state) },
  boolean: /verdadeiro|falso/,
  arithmeticOperators: ['+', '-', '*', '/', '%', '**'],
  incrementDecrementOperators: ['++', '--'],
  assignmentOperators: ['=', '+=', '-=', '*=', '/=', '%=', '**='],
  comparisonOperators: ['==', '!=', '===', '!==', '>', '<', '>=', '<='],
  logicalOperators: ['&&', '||', '!'],
  bitwiseOperators: ['&', '|', '^', '~', '<<', '>>', '>>>'],
  otherOperators: [',', '.', '?:', ':'],
  leftParentheses: '(',
  rightParentheses: ')',
  leftBracket: '{',
  rightBracket: '}',
  comment: /#.*/,
  stringChar: /".*"/,
  whitespace: {
    match: /\s+/,
    lineBreaks: true,
  },
  identifier: {
    match: /(?<!#\s*)\b[a-zA-Z_]\w*\b/,
  },
  endProgram: /\beeee amigos acabou/,
};
